### ISSUE TITLE
release dataset as first milestone?

### ISSUE THREAD

**Issue by rbroc** [rbroc/echo#15]
we could consider releasing the datasets (& dataset generation/expansion code) as first milestone for the project -- independently of the experiment and predictive modeling part of the project, this could be a valuable resource and a nice publication (LREC?) per se.

**Comment by MinaAlmasi** [comment]
Will be working on creating a dataset with all four datasets (dailydialog etc.) and models (humans included) represented in a giant file with the completions and another giant file for the metrics i.e., 
1. text_dataset.jsonl (or .parquet)
2. metrics_dataset.jsonl

Then a user can do whatever they want with it (stratify by dataset or model and classify). This is also done to make the classify pipeline more robust (#70). Hope is to get the dataset uploaded to HF at some point (but we'll probably regenerate data with new models before that).

**Comment by MinaAlmasi** [comment]
Sort of done this with #73 - we may want to uploade the train/test/val splits to HF when done
